from setuptools import find_packages, setup

setup(
    name="audio_utils",
    version="1.0.0",
    url="https://github.com/stefantaubert/audio-utils.git",
    author="Stefan Taubert",
    author_email="stefan.taubert@posteo.de",
    description="Utils for audio processing",
    packages=["audio_utils"],
    install_requires=[
        "appdirs",
        "audioread",
        "certifi",
        "cffi",
        "chardet",
        "cycler",
        "decorator",
        "idna",
        "joblib",
        "kiwisolver",
        "librosa",
        "llvmlite",
        "matplotlib",
        "numba",
        "numpy",
        "packaging",
        "pillow",
        "pooch",
        "pycparser",
        "pyparsing",
        "python-dateutil",
        "requests",
        "resampy",
        "scikit-learn",
        "scipy",
        "six",
        "soundfile",
        "threadpoolctl",
        "torch<=1.7.1",
        "tqdm",
        "typing-extensions",
        "urllib3",
    ],
)
